name: CI/CD for Task Files

on:
  push:
    paths:
      - '**/devops_*.php'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL
        run: |
          choco install mysql
          Write-Host "MySQL installed"

      - name: Set up MySQL path
        run: |
          $env:PATH += ";C:\tools\mysql\bin"
          Write-Host "Updated PATH: $env:PATH"

      - name: Verify MySQL executable
        run: |
          Get-ChildItem -Path "C:\tools\mysql\bin"
          if (-Not (Test-Path "C:\tools\mysql\bin\mysql.exe")) {
              Write-Error "MySQL executable not found at C:\tools\mysql\bin\mysql.exe"
              exit 1
          }

      - name: Print current directory and list files
        run: |
          Get-ChildItem -Recurse

      - name: Identify changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: '**/devops_*.php'

      - name: Run deployment script
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          pwsh deploy.ps1 -changedFiles "${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Save deployment report
        uses: actions/upload-artifact@v2
        with:
          name: deployment-report
          path: report.txt
