name: CI/CD Pipeline

on:
  push:
    paths:
      - '**/devops_*.php'

jobs:
  build:
    runs-on: windows-latest  # تحديد نظام التشغيل ويندوز

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate PHP syntax
        shell: pwsh  # استخدام PowerShell
        run: |
          echo "Validating PHP syntax"
          Get-ChildItem -Path . -Filter 'devops_*.php' -Recurse | ForEach-Object {
              php -l $_.FullName
          }

      - name: Run tests
        shell: pwsh  # استخدام PowerShell
        run: |
          echo "Running tests"
          if (Test-Path "tests") {
              ./tests/run-tests.sh
          } else {
              echo "No tests directory found, skipping tests."
          }

      - name: Deploy to Local Server via HTTPS
        env:
          GITHUB_USERNAME: mohmadit
          GITHUB_PASSWORD: 10200102qwe!@#
        shell: pwsh  # استخدام PowerShell
        run: |
          echo "Deploying to local server via HTTPS"
          $baseUrl = "http://127.0.0.1/aqdevops"
          $repoUrl = "$baseUrl.git"
          
          # Configure Git with HTTPS credentials
          git config --global credential.helper store
          git config --global user.name "$env:GITHUB_USERNAME"
          git config --global user.password "$env:GITHUB_PASSWORD"
          
          # Pull latest changes from main branch
          git pull $repoUrl main
