name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.21'

    - name: Run custom script
      run: |
        file_path="${GITHUB_WORKSPACE}/${{ env.project_folder }}/devops_${{ env.task_title }}_${{ env.task_id }}_${{ env.task_code_id }}_${{ env.publish_type }}.php"
        if [ ! -f "$file_path" ]; then
          echo "File $file_path does not exist."
          exit 1
        fi
        content=$(cat "$file_path")
        if [[ ! "$content" =~ "<\?php" ]]; then
          echo "File $file_path does not contain PHP opening tag."
          exit 1
        fi
        if [[ ! "$content" =~ "\?>" ]]; then
          echo "File $file_path does not contain PHP closing tag."
          exit 1
        fi
        echo "File $file_path contains valid PHP tags."
