name: CI/CD for Task Files

on:
  push:
    paths:
      - '**/devops_*.php'
  pull_request:
    paths:
      - '**/devops_*.php'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install

    - name: List files in workspace
      run: |
        find . -name 'devops_*.php'

    - name: Ensure tests directory exists
      run: |
        if [ -d "$GITHUB_WORKSPACE/tests" ]; then
          echo "Tests directory exists."
        else
          echo "Tests directory not found!"
          exit 1
        fi

    - name: Run tests on modified file
      run: |
        TARGET_FILE=$(git diff --name-only ${{ github.sha }} ${{ github.event.before }} | grep 'devops_.*\.php' | head -n 1)
        if [ -z "$TARGET_FILE" ]; then
          echo "No devops files modified."
          exit 1
        else
          echo "Running tests on $TARGET_FILE"
          TARGET_FILE=$TARGET_FILE php vendor/bin/phpunit --configuration phpunit.xml --filter DevOpsFileTest
        fi
