name: Publish to Local Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PowerShell
      uses: actions/setup-powershell@v2

    - name: Set LATEST_FILE environment variable
      run: echo "LATEST_FILE=latest_file.php" >> $GITHUB_ENV

    - name: Check if file exists and validate PHP tags
      shell: pwsh
      run: |
        if (-not (Test-Path "$env:LATEST_FILE")) {
          Write-Error "File $env:LATEST_FILE does not exist."
          exit 1
        }
        $content = Get-Content -Path $env:LATEST_FILE
        if (-not ($content -match '<\?php')) {
          Write-Error "File $env:LATEST_FILE does not contain PHP opening tag."
          exit 1
        }
        if (-not ($content -match '\?>')) {
          Write-Error "File $env:LATEST_FILE does not contain PHP closing tag."
          exit 1
        }
        Write-Host "File $env:LATEST_FILE contains valid PHP tags."
      env:
        LATEST_FILE: ${{ env.LATEST_FILE }}

    - name: Upload file to local server
      run: |
        $url = "http://127.0.0.1/aqdevops/receive_file.php"
        Invoke-RestMethod -Uri $url -Method Post -InFile $env:LATEST_FILE -ContentType "multipart/form-data"
      env:
        LATEST_FILE: ${{ env.LATEST_FILE }}

    - name: Notify completion
      run: echo "File successfully uploaded to local server."
      env:
        LATEST_FILE: ${{ env.LATEST_FILE }}
