name: CI/CD Pipeline

on:
  push:
    paths:
      - '**/devops_*.php'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Extract Task ID from file name
        id: extract_task_id
        shell: pwsh
        run: |
          $fileName = (Get-ChildItem -Path . -Filter 'devops_*.php' -Recurse | Select-Object -First 1).Name
          Write-Host "Found file: $fileName"
          if ($fileName -match 'devops_add_(\d+)') {
              $taskId = $matches[1]
              Write-Host "Extracted Task ID: $taskId"
              echo "::set-output name=task_id::$taskId"
          } else {
              Write-Error "Failed to extract Task ID from file name: $fileName"
              exit 1
          }

      - name: Validate PHP syntax
        id: validate
        shell: pwsh
        run: |
          echo "Validating PHP syntax"
          $result = ""
          Get-ChildItem -Path . -Filter 'devops_*.php' -Recurse | ForEach-Object {
              $result += php -l $_.FullName + "`n"
          }
          echo "::set-output name=validation_result::$result"

      - name: Run tests
        id: tests
        shell: pwsh
        run: |
          echo "Running tests"
          $result = ""
          if (Test-Path "tests") {
              $result = ./tests/run-tests.sh
          } else {
              $result = "No tests directory found, skipping tests."
          }
          echo "::set-output name=test_result::$result"

      - name: Send results to API
        shell: pwsh
        run: |
          $task_id = "${{ steps.extract_task_id.outputs.task_id }}"
          $validation_results = "${{ steps.validate.outputs.validation_result }}"
          $test_results = "${{ steps.tests.outputs.test_result }}"
          $payload = @{
              task_id = $task_id
              validation_results = $validation_results
              test_results = $test_results
          } | ConvertTo-Json
          
          Invoke-RestMethod -Uri 'http://127.0.0.1/aqdevops/api/save_results.php' -Method Post -Body $payload -ContentType 'application/json'
