name: CI/CD for Task Files

on:
  push:
    paths:
      - '**/devops_*.php'
  pull_request:
    paths:
      - '**/devops_*.php'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install

    - name: Ensure tests directory exists
      run: |
        Write-Host "Checking for tests directory..."
        if (Test-Path -Path "$env:GITHUB_WORKSPACE/tests") {
          Write-Host "Tests directory exists."
        } else {
          Write-Error "Tests directory not found!"
          exit 1
        }
      shell: pwsh

    - name: Run tests
      run: php vendor\bin\phpunit --configuration phpunit.xml

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy code
      run: echo "Deploying your code..."
