name: CI/CD for Task Files

on:
  push:
    paths:
      - '**/devops_*.php'
  pull_request:
    paths:
      - '**/devops_*.php'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install

    - name: List files in workspace
      run: ls -R
      shell: bash

    - name: Ensure tests directory exists
      run: |
        if [ -d "tests" ]; then
          echo "Tests directory exists."
        else
          echo "Tests directory not found!"
          exit 1
        fi
      shell: bash

    - name: Identify changed files
      id: changed-files
      uses: tj-actions/changed-files@v34
      with:
        files: '**/devops_*.php'

    - name: Run tests on changed files
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        for file in $(echo ${{ steps.changed-files.outputs.all_changed_files }}); do
          echo "Testing $file"
          php -l $file
          # Check for PHP tags
          if grep -q '<?php' "$file" && grep -q '?>' "$file"; then
            echo "PHP opening and closing tags found in $file"
          else
            echo "PHP opening or closing tag not found in $file"
            exit 1
          fi

          # Optional check for PHP functions
          if grep -q 'function' "$file"; then
            echo "PHP functions found in $file"
          else
            echo "No PHP functions found in $file, but continuing..."
          fi
        done
      shell: bash

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install lftp
      run: sudo apt-get install -y lftp

    - name: Test FTP connection
      env:
        FTP_SERVER: "127.0.0.1"
        FTP_USERNAME: "mohamad"
        FTP_PASSWORD: "10200102ma!@#"
        FTP_PORT: "21"
        REMOTE_PATH: "/D:/xampp/htdocs/aqdevops/results_deploy"
      run: |
        echo "Starting FTP connection test..."
        lftp -u $FTP_USERNAME,$FTP_PASSWORD -p $FTP_PORT $FTP_SERVER -e "
        mkdir -p $REMOTE_PATH/test_connection
        cd $REMOTE_PATH/test_connection
        ls
        rm -r $REMOTE_PATH/test_connection
        bye
        "
        echo "FTP connection test completed."

    - name: Deploy code
      env:
        FTP_SERVER: "127.0.0.1"
        FTP_USERNAME: "mohamad"
        FTP_PASSWORD: "10200102ma!@#"
        FTP_PORT: "21"
        REMOTE_PATH: "/D:/xampp/htdocs/aqdevops/results_deploy"
      run: |
        echo "Starting FTP deployment..."
        lftp -u $FTP_USERNAME,$FTP_PASSWORD -p $FTP_PORT $FTP_SERVER -e "
        mirror -R $GITHUB_WORKSPACE $REMOTE_PATH
        bye
        "
        echo "FTP deployment completed."
