name: CI/CD for Task Files

on:
  push:
    paths:
      - '**/devops_*.php'
  pull_request:
    paths:
      - '**/devops_*.php'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install

    - name: List files in workspace
      run: ls -R
      shell: bash

    - name: Ensure tests directory exists
      run: |
        if [ -d "tests" ]; then
          echo "Tests directory exists."
        else
          echo "Tests directory not found!"
          exit 1
        fi
      shell: bash

    - name: Identify changed files
      id: changed-files
      uses: tj-actions/changed-files@v34
      with:
        files: '**/devops_*.php'

    - name: Run tests on changed files
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        for file in $(echo ${{ steps.changed-files.outputs.all_changed_files }}); do
          echo "Testing $file"
          php -l $file
          if grep -q '<?php' "$file" && grep -q '?>' "$file"; then
            echo "PHP opening and closing tags found in $file"
          else
            echo "PHP opening or closing tag not found in $file"
            exit 1
          fi

          if grep -q 'function' "$file"; then
            echo "PHP functions found in $file"
          else
            echo "No PHP functions found in $file, but continuing..."
          fi
        done
      shell: bash

    - name: Build Project
      run: |
        echo "Building the project..."
        # أضف هنا أي أوامر بناء تحتاجها لمشروعك
      shell: bash

    - name: Copy test results to deploy directory
      run: |
        mkdir -p D:/xampp/htdocs/aqdevops/results_deploy
        if [ -d "tests" ]; then
          cp -r tests/* D:/xampp/htdocs/aqdevops/results_deploy/
        else
          echo "Tests directory not found!"
          exit 1
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: D:/xampp/htdocs/aqdevops/results_deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: test-results
        path: ./results

    - name: Deploy to local FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: "ftp://127.0.0.1"
        username: "user"
        password: "12345"  # كلمة المرور الخاصة بك
        local-dir: "./results"
        server-dir: "D:/xampp/htdocs/aqdevops/results_deploy/"

    - name: Deploy PHP files to local server
      env:
        LOCAL_SERVER_URL: "http://127.0.0.1/aqdevops/upload.php"
        DEPLOY_TOKEN: "" # ترك التوكن فارغًا لأنك لا تحتاج إليه
      run: |
        echo "Starting deployment to local server..."
        for file in $(git diff --name-only HEAD^ HEAD | grep 'devops_*.php'); do
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$LOCAL_SERVER_URL" \
          -F "file=@$file" \
          -F "token=$DEPLOY_TOKEN")
          if [ $response -eq 200 ]; then
            echo "File $file uploaded successfully."
          else
            echo "Failed to upload file $file. HTTP response code: $response"
          fi
        done
        echo "Deployment to local server completed."
