name: CI/CD for Task Files

on:
  push:
    paths:
      - '**/tasks/*.php'  # تحديث المسار ليشمل ملفات المهام فقط

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate PHP syntax
        shell: pwsh
        run: |
          echo "Validating PHP syntax"
          Get-ChildItem -Path . -Filter 'tasks/*.php' -Recurse | ForEach-Object {
              php -l $_.FullName
          }

      - name: Run tests
        shell: pwsh
        run: |
          echo "Running tests"
          if (Test-Path "tests") {
              ./tests/run-tests.sh
          } else {
              echo "No tests directory found, skipping tests."
          }

      - name: Verify SSH connection
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        shell: pwsh
        run: |
          echo "Verifying SSH connection"
          $sshFolderPath = "$env:USERPROFILE\.ssh"
          if (-not (Test-Path $sshFolderPath)) {
              New-Item -Path $sshFolderPath -ItemType Directory
          }

          $idRsaFilePath = "$sshFolderPath\id_rsa"
          $idRsaContent = [System.Convert]::FromBase64String($env:DEPLOY_KEY)
          [System.IO.File]::WriteAllBytes($idRsaFilePath, $idRsaContent)
          (Get-Item $idRsaFilePath).Attributes = 'ReadOnly'
          $acl = Get-Acl $idRsaFilePath
          $accessRule = New-Object System.Security.AccessControl.FileSystemAccessRule("Everyone", "FullControl", "None", "None", "Allow")
          $acl.SetAccessRule($accessRule)
          Set-Acl $idRsaFilePath $acl

          ssh-keyscan -H 127.0.0.1 >> "$sshFolderPath\known_hosts"
          ssh -i $idRsaFilePath -o StrictHostKeyChecking=no user@127.0.0.1 "echo 'SSH connection successful'"

      - name: Deploy to Local Server
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        shell: pwsh
        run: |
          echo "Deploying to local server"
          ssh -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no user@127.0.0.1 "cd /d/xampp/htdocs/aqdevops && git pull origin main"
