name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      file_path:
        description: 'File path'
        required: true
        default: 'project_folder/devops_task_title_task_id_code_id_publish_type.php'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate PHP file
      run: |
        $file_path = '${{ github.event.inputs.file_path }}'
        if (-not (Test-Path $file_path)) {
          Write-Error "File $file_path does not exist."
          exit 1
        }
        $content = Get-Content -Path $file_path
        if (-not ($content -match '<\?php')) {
          Write-Error "File $file_path does not contain PHP opening tag."
          exit 1
        }
        if (-not ($content -match '\?>')) {
          Write-Error "File $file_path does not contain PHP closing tag."
          exit 1
        }
        Write-Host "File $file_path contains valid PHP tags."

    - name: Run tests
      run: |
        # Add your test commands here
        Write-Host "Running tests..."

    - name: Notify completion
      run: echo "CI job completed."
