name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  check_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for PHP files
        run: |
          CHANGED_FILE=$(git diff --name-only HEAD~1 HEAD | grep 'devops_.*\.php' || true)
          if [ -z "$CHANGED_FILE" ]; then
            echo "No matching PHP files changed."
            exit 0
          fi
          echo "CHANGED_FILE=${CHANGED_FILE}" >> $GITHUB_ENV
        shell: bash

      - name: Show changed file
        run: echo "Changed file:${{ env.CHANGED_FILE }}"
        env:
          CHANGED_FILE: ${{ env.CHANGED_FILE }}

      - name: Process PHP file
        if: env.CHANGED_FILE
        run: |
          if [ ! -f "${{ env.CHANGED_FILE }}" ]; then
            echo "File ${{ env.CHANGED_FILE }} does not exist."
            exit 1
          fi
          # أضف هنا كود معالجة الملف المطلوب
          echo "Processing file ${{ env.CHANGED_FILE }}"
        env:
          CHANGED_FILE: ${{ env.CHANGED_FILE }}

      - name: Create a release
        if: env.CHANGED_FILE
        run: |
          TAG_NAME="v1.0.$(date +%s)"
          RELEASE_NAME="Release for file ${{ env.CHANGED_FILE }}"
          RELEASE_BODY="This release contains the updated code for ${{ env.CHANGED_FILE }}."
          curl -X POST -H "Authorization: token ${{ secrets.TOKEN }}" \
              -d "{\"tag_name\": \"$TAG_NAME\", \"target_commitish\": \"main\", \"name\": \"$RELEASE_NAME\", \"body\": \"$RELEASE_BODY\", \"draft\": false, \"prerelease\": false}" \
              https://api.github.com/repos/${{ github.repository }}/releases
