name: CI/CD Pipeline

on:
  push:
    paths:
      - '**/devops_*.php'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Validate PHP syntax
        shell: pwsh
        run: |
          echo "Validating PHP syntax"
          $result = ""
          Get-ChildItem -Path . -Filter 'devops_*.php' -Recurse | ForEach-Object {
              $result += php -l $_.FullName + "`n"
          }
          echo "result=$result" >> $GITHUB_ENV

      - name: Run tests
        shell: pwsh
        run: |
          echo "Running tests"
          if (Test-Path "tests") {
              $result = ./tests/run-tests.sh
          } else {
              $result = "No tests directory found, skipping tests."
          }
          echo "test_result=$result" >> $GITHUB_ENV

      - name: Send results to API
        shell: pwsh
        run: |
          $validation_results = "${{ env.result }}"
          $test_results = "${{ env.test_result }}"
          $payload = @{
              task_id = ${{ github.event.inputs.task_id }}
              validation_results = $validation_results
              test_results = $test_results
          } | ConvertTo-Json

          Invoke-RestMethod -Uri 'http://127.0.0.1/aqdevops/api/save_results.php' -Method Post -Body $payload -ContentType 'application/json'
