name: CI/CD for Task Files

on:
  push:
    paths:
      - '**/devops_*.php'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.21'

      - name: Install dependencies
        run: composer install

      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit

      - name: Find latest devops file
        id: find_latest_file
        run: |
          latest_file=$(git log -m -1 --name-only --pretty=format: | grep 'devops_.*\.php' | head -n 1 || true)
          if [ -z "$latest_file" ]; then
            echo "No devops_*.php file found in the latest commit."
            exit 1
          fi
          echo "LATEST_FILE=$latest_file" >> $GITHUB_ENV
        shell: bash

      - name: Display latest file for debugging
        run: echo "Latest file:${{ env.LATEST_FILE }}"

      - name: Validate PHP file structure
        run: |
          if [ ! -f "$LATEST_FILE" ]; then
            echo "File $LATEST_FILE does not exist."
            exit 1
          fi

          if ! grep -q "<?php" "$LATEST_FILE"; then
            echo "File $LATEST_FILE does not contain PHP opening tag."
            exit 1
          fi

          if ! grep -q "?>" "$LATEST_FILE"; then
            echo "File $LATEST_FILE does not contain PHP closing tag."
            exit 1
          fi

          echo "File $LATEST_FILE contains valid PHP tags."
        env:
          LATEST_FILE: ${{ env.LATEST_FILE }}

      - name: Run PHP lint
        run: php -l ${{ env.LATEST_FILE }}
        env:
          LATEST_FILE: ${{ env.LATEST_FILE }}

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
        env:
          LATEST_FILE: ${{ env.LATEST_FILE }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: "Release ${{ github.run_number }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.LATEST_FILE }}
          asset_name: $(basename ${{ env.LATEST_FILE }})
          asset_content_type: application/php
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
