name: CI/CD for Task Files

on:
  push:
    paths:
      - '**/devops_*.php'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL
        run: |
          choco install mysql -y
          Write-Host "MySQL installed"

      - name: Verify MySQL installation path
        run: |
          $mysqlPath = (Get-Command mysql.exe).Path
          Write-Host "MySQL installation path: $mysqlPath"
          if (-Not $mysqlPath) {
              Write-Error "MySQL installation path not found"
              exit 1
          }

      - name: Set up MySQL path
        run: |
          $mysqlPath = (Get-Command mysql.exe).Path
          $mysqlBinPath = [System.IO.Path]::GetDirectoryName($mysqlPath)
          $env:PATH += ";$mysqlBinPath"
          Write-Host "Updated PATH: $env:PATH"

      - name: Verify MySQL executable
        run: |
          $mysqlPath = (Get-Command mysql.exe).Path
          if (-Not (Test-Path $mysqlPath)) {
              Write-Error "MySQL executable not found at $mysqlPath"
              exit 1
          }
          Get-ChildItem -Path $mysqlPath

      - name: Print current directory and list files
        run: |
          Get-ChildItem -Recurse

      - name: Identify changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: '**/devops_*.php'

      - name: Run deployment script
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          pwsh deploy.ps1 -changedFiles "${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Save deployment report
        uses: actions/upload-artifact@v2
        with:
          name: deployment-report
          path: report.txt
