name: CI/CD for Task Files

on:
  push:
    paths:
      - '**/devops_*.php'
  pull_request:
    paths:
      - '**/devops_*.php'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install

    - name: List modified files
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'devops_.*\.php' > modified_files.txt
        cat modified_files.txt

    - name: Ensure tests directory exists
      run: |
        if [ -d "$GITHUB_WORKSPACE/tests" ]; then
          echo "Tests directory exists."
        else
          echo "Tests directory not found!"
          exit 1
        fi

    - name: Run tests on modified files
      run: |
        if [ -s modified_files.txt ]; then
          while IFS= read -r TARGET_FILE; do
            echo "Running tests on $TARGET_FILE"
            php vendor/bin/phpunit --configuration phpunit.xml --log-junit junit-report.xml "$TARGET_FILE"
          done < modified_files.txt
        else
          echo "No devops files modified."
          exit 1
        fi
