name: CI

on:
  workflow_dispatch:
    inputs:
      project_folder:
        description: 'Project folder'
        required: true
      task_title:
        description: 'Task title'
        required: true
      task_id:
        description: 'Task ID'
        required: true
      task_code_id:
        description: 'Task code ID'
        required: true
      publish_type:
        description: 'Publish type'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.21'

    - name: Run custom script
      run: |
        file_path="${{ github.workspace }}/${{ github.event.inputs.project_folder }}/devops_${{ github.event.inputs.task_title }}_${{ github.event.inputs.task_id }}_${{ github.event.inputs.task_code_id }}_${{ github.event.inputs.publish_type }}.php"
        echo "Checking if file exists: $file_path"
        if [ ! -f "$file_path" ]; then
          echo "File $file_path does not exist."
          exit 1
        fi
        echo "File $file_path exists, reading content..."
        content=$(cat "$file_path")
        echo "File content: $content"
        
        new_file_path="${{ github.workspace }}/${{ github.event.inputs.project_folder }}/new_${{ github.event.inputs.task_title }}_${{ github.event.inputs.task_id }}_${{ github.event.inputs.task_code_id }}_${{ github.event.inputs.publish_type }}.php"
        echo "Saving content to new file: $new_file_path"
        echo "$content" > "$new_file_path"
        echo "New file content: $(cat "$new_file_path")"

      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
