name: CI/CD Pipeline

on:
  push:
    paths:
      - '**/devops_*.php'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate PHP syntax
        shell: pwsh
        run: |
          echo "Validating PHP syntax" > validation_results.txt
          Get-ChildItem -Path . -Filter 'devops_*.php' -Recurse | ForEach-Object {
              php -l $_.FullName >> validation_results.txt
          }

      - name: Run tests
        shell: pwsh
        run: |
          echo "Running tests" > test_results.txt
          if (Test-Path "tests") {
              ./tests/run-tests.sh >> test_results.txt
          } else {
              echo "No tests directory found, skipping tests." >> test_results.txt
          }

      - name: Upload validation results artifact
        uses: actions/upload-artifact@v2
        with:
          name: validation_results
          path: validation_results.txt

      - name: Upload test results artifact
        uses: actions/upload-artifact@v2
        with:
          name: test_results
          path: test_results.txt
