name: CI/CD for Task Files

on:
  push:
    paths:
      - '**/devops_*.php'
  pull_request:
    paths:
      - '**/devops_*.php'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

      - name: List files in workspace
        run: Get-ChildItem -Recurse

      - name: Ensure tests directory exists
        run: |
          if (Test-Path -Path "tests") {
            Write-Output "Tests directory exists."
          } else {
            Write-Output "Tests directory not found!"
            exit 1

      - name: Identify changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: '**/devops_*.php'

      - name: Run tests on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          $changedFiles = "${{ steps.changed-files.outputs.all_changed_files }}".Split("`n")
          foreach ($file in $changedFiles) {
            Write-Output "Testing $file"
            php -l $file
            if ((Get-Content $file) -match '<\?php' -and (Get-Content $file) -match '\?>') {
              Write-Output "PHP opening and closing tags found in $file"
            } else {
              Write-Output "PHP opening or closing tag not found in $file"
              exit 1
            }

            if ((Get-Content $file) -match 'function') {
              Write-Output "PHP functions found in $file"
            } else {
              Write-Output "No PHP functions found in $file, but continuing..."
            }

      - name: Build Project
        run: Write-Output "Building the project..."

      - name: Ensure results directory exists on local server
        run: |
          if (-Not (Test-Path -Path "D:/xampp/htdocs/aqdevops/results_deploy")) {
            New-Item -ItemType Directory -Path "D:/xampp/htdocs/aqdevops/results_deploy"
          }

      - name: Deploy files to local server
        run: |
          $changedFiles = "${{ steps.changed-files.outputs.all_changed_files }}".Split("`n")
          foreach ($file in $changedFiles) {
            Write-Output "Deploying $file"
            curl -F "file=@$file" http://127.0.0.1/upload.php
          }
