name: CI/CD for Task Files

on:
  push:
    paths:
      - '**/devops_*.php'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12'

      - name: Validate PHP syntax
        run: |
          echo "Validating PHP syntax"
          find . -name 'devops_*.php' -exec php -l {} \;

      - name: Run tests
        run: |
          echo "Running tests"
          if [ -d "tests" ]; then
            ./tests/run-tests.sh
          else
            echo "No tests directory found, skipping tests."
          fi

      - name: Deploy to server
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "Starting deployment"
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H <ngrok_address> >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -v user@<ngrok_address> "echo 'SSH connection successful'" || { echo 'SSH connection failed'; exit 1; }
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -v" ./ user@<ngrok_address>:/path/to/deployment
          echo "Deployment completed"
