name: CI

on:
  workflow_dispatch:
    inputs:
      project_folder:
        description: 'Project folder'
        required: true
      task_title:
        description: 'Task title'
        required: true
      task_id:
        description: 'Task ID'
        required: true
      task_code_id:
        description: 'Task code ID'
        required: true
      publish_type:
        description: 'Publish type'
        required: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install

    - name: Run unit tests (Optional)
      run: |
        echo "Running PHPUnit tests"
        vendor/bin/phpunit --configuration phpunit.xml || true # لا تفشل إذا فشلت الاختبارات الوظيفية

  run_structural_tests:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install

    - name: Install htmlhint
      run: npm install -g htmlhint

    - name: Run structural tests
      run: |
        echo "Running structural tests"
        file_path="${{ github.workspace }}/${{ github.event.inputs.project_folder }}/devops_${{ github.event.inputs.task_title }}_${{ github.event.inputs.task_id }}_${{ github.event.inputs.task_code_id }}_${{ github.event.inputs.publish_type }}.php"
        echo "Checking if file exists: $file_path"
        if [ ! -f "$file_path" ]; then
          echo "File $file_path does not exist."
          exit 1
        fi
        
        echo "File $file_path exists, checking content..."
        content=$(cat "$file_path")

        # Check if the file is a PHP file
        if [[ "$content" == *"<?php"* ]]; then
          echo "PHP file detected, checking syntax..."
          php -l "$file_path"
          if [ $? -ne 0 ]; then
            echo "PHP syntax errors found."
            exit 1
          fi
          echo "PHP syntax is valid."
        
        # Check if the file is an HTML/CSS file
        elif [[ "$content" == *"<html"* || "$content" == *"<div"* || "$content" == *"<head"* || "$content" == *"<style"* ]]; then
          echo "HTML/CSS structure detected, checking syntax..."
          htmlhint "$file_path"
          if [ $? -ne 0 ]; then
            echo "HTML structure errors found."
            exit 1
          fi
          echo "HTML structure is valid."
        
        else
          echo "Unknown file structure. Neither PHP nor HTML/CSS detected."
          exit 1
        fi

        echo "Structural tests passed."

  run_custom_script:
    runs-on: ubuntu-latest
    needs: run_structural_tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install

    - name: Run custom script
      run: |
        file_path="${{ github.workspace }}/${{ github.event.inputs.project_folder }}/devops_${{ github.event.inputs.task_title }}_${{ github.event.inputs.task_id }}_${{ github.event.inputs.task_code_id }}_${{ github.event.inputs.publish_type }}.php"
        echo "Checking if file exists: $file_path"
        if [ ! -f "$file_path" ]; then
          echo "File $file_path does not exist."
          exit 1
        fi
        echo "File $file_path exists, reading content..."
        content=$(cat "$file_path")
        echo "File content: $content"
        
        new_file_path="${{ github.workspace }}/${{ github.event.inputs.project_folder }}/devops_${{ github.event.inputs.task_title }}_${{ github.event.inputs.task_id }}_${{ github.event.inputs.task_code_id }}_${{ github.event.inputs.publish_type }}.php"
        echo "Saving content to new file: $new_file_path"
        echo "$content" > "$new_file_path"
        echo "New file content: $(cat "$new_file_path")"

  deploy_to_server:
    runs-on: ubuntu-latest
    needs: run_custom_script

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install

    - name: Deploy to server
      run: |
        file_path="${{ github.workspace }}/${{ github.event.inputs.project_folder }}/devops_${{ github.event.inputs.task_title }}_${{ github.event.inputs.task_id }}_${{ github.event.inputs.task_code_id }}_${{ github.event.inputs.publish_type }}.php"
        echo "Deploying to local server"
        response=$(curl -X POST -F "file=@$file_path"   https://c6a7-31-9-75-215.ngrok-free.app/aqdevops/upload.php)
        echo "Server response: $response"
        if [[ "$response" != *"File uploaded successfully."* ]]; then
          echo 'Failed to deploy to local server'
          exit 1
        fi
        echo "File deployed successfully to: $file_path"

      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
