name: CI/CD for Task Files

on:
  push:
    paths:
      - '**/devops_*.php'
  pull_request:
    paths:
      - '**/devops_*.php'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

      - name: Copy test results to deploy directory
        run: |
          if (-Not (Test-Path -Path "results_deploy")) {
            New-Item -ItemType Directory -Path "results_deploy"
          }
          if (Test-Path -Path "tests") {
            Copy-Item -Path "tests/*" -Destination "results_deploy/"
          } else {
            Write-Output "Tests directory not found!"
            exit 1
          }

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: results_deploy/

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: ./results

      - name: Upload file to local server
        run: |
          $files = Get-ChildItem -Path "./results"
          foreach ($file in $files) {
            $filePath = $file.FullName
            Write-Output "Uploading $filePath"
            $response = curl -X POST -F "file=@$filePath" http://127.0.0.1/aqdevops/upload.php -v
            Write-Output "cURL response: $response"
          }
        shell: pwsh
